name: mentora
description: Mentora - Real-time team communication platform
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.1
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.2
  pusher_channels_flutter: ^2.2.0
  file_picker: ^8.0.0
  audioplayers: ^6.1.0
  record: ^6.1.2
  photo_view: ^0.15.0
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^18.0.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  connectivity_plus: ^6.1.1
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.0
  timeago: ^3.6.1
  url_launcher: ^6.2.5
  mime: ^1.0.5
  path: ^1.9.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
